### ISSUE TITLE
Problems with Path configuration on my localhost (MAMP)

### ISSUE THREAD

**Issue by noxify** [atomicon/codeigniter-theme#1]
Hi,

i play around with your theme library.

And i found a small "bug" in the /config/theme.php.

In the OOTB installation, the path definition for the themes directory is the following:

```
$config['theme']['path'] = trim(FCPATH, '\\/ ') . '/themes/';
```

But on my localhost i will see always a error message

```
Make sure you configurate your theme (did you copy the themes folder to your root?)
Applications/MAMP/htdocs/XX/ci_dev/themes/default/index.php not found.
```

There is a missing leading slash. After changing the line in the /config/theme.php to the following
it works fine.

```
 $config['theme']['path'] = FCPATH . 'themes/';
```

Maybe it helps someone with the same error :)

Thanks a lot!

Regards,
Marcus

**Comment by atomicon** [comment]
Thank you! I updated the code and tested it on a windows-machine and a macbook.

https://github.com/atomicon/codeigniter-theme/commit/25e41d4f7ac38e282cb4f43ccd390c1b7b2c17f6

**Comment by atomicon** [comment]
Hey Marcus!

Thank you, I updated the code and tested it on a windows-machine and a  
macbook.
Works perfectly.

https://github.com/atomicon/codeigniter-theme/commit/25e41d4f7ac38e282cb4f43ccd390c1b7b2c17f6

Regards,
Yvo

https://github.com/atomicon/codeigniter-theme/commit/25e41d4f7ac38e282cb4f43ccd390c1b7b2c17f6

Quoting Marcus Reinhardt  
reply@reply.github.com:
