### ISSUE TITLE
Problem : Path config (LINUX)

### ISSUE THREAD

**Issue by Kristories** [atomicon/codeigniter-theme#3]
Issue 

```
$config['theme']['path'] = trim(FCPATH, '\\/ ') . '/themes/';
```

Solution

```
$config['theme']['path'] = FCPATH  . '/themes/';
```

**Comment by atomicon** [comment]
Hey Kristories,

Updated the config with your solution. 
Also works fine on mac & pc systems, no clue why linux was acting strange?

anyway: pushed
https://github.com/atomicon/codeigniter-theme/blob/master/config/theme.php
