### ISSUE TITLE
Request asset library

### ISSUE THREAD

**Issue by Kristories** [atomicon/codeigniter-theme#5]
Request for assets library that has the ability to combine and minify Javascript and CSS assets. Additionally there's a LessCSS compiler and a CoffeeScript compiler.

**Comment by atomicon** [comment]
Hey Kristories, there is already a package with your needs

Take a look here:
http://bstrahija.github.com/assets/

Or via sparks:
http://getsparks.org/packages/assets/versions/HEAD/show
