### ISSUE TITLE
Unable to load the requested class: Theme

### ISSUE THREAD

**Issue by xenuser** [atomicon/codeigniter-theme#8]
First of all: Thank you for your work and for providing your stuff for free!

When installing the codeigniter-theme stuff, I receive the following message when browsing my codeigniter project in my browser:

Unable to load the requested class: Theme

For me, this looks like some sort of spelling/typing issue (e.g. windows camel case sensitivity vs. Linux typing sensitivity).

**Comment by KWDesigns** [comment]
did you autoload the theme library and add the theme to the autoload config?

**Comment by xenuser** [comment]
Sorry for the late reply. To be honest, I think I did all that, but I switched to another framework in the meantime.
